repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [pyskoob]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        # Run tests in an isolated environment with Python 3.11 and dev extras
        entry: uv run --python 3.11 --no-project --isolated --with-editable .[dev] pytest
        language: system
        types: [python]
        pass_filenames: false
