site_name: PySkoob
repo_url: https://github.com/victor-soeiro/pyskoob
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Services:
      - Author Service: author_service.md
      - Books Service: books_service.md
      - Publisher Service: publishers_service.md
      - Users Service: users_service.md
      - Profile Service: profile_service.md
  - Advanced Usage: advanced_usage.md
  - Stable Public API: stable_api.md
  - Contributing: contributing.md
markdown_extensions:
  - admonition
  - codehilite
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
