name: Delete Codex Branches

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'codex/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${context.payload.pull_request.head.ref}`
            });
