name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'SemVer bump type'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install bump-my-version==1.2.1 build mkdocs mkdocs-material 'mkdocstrings[python]'
          sudo apt-get update && sudo apt-get install -y jq

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        id: bump
        run: |
          bump-my-version bump ${{ github.event.inputs.bump }} --allow-dirty
          new_version=$(bump-my-version show current_version --format json | jq -r '.current_version')
          echo "version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Tag and push
        run: |
          git tag "v${{ steps.bump.outputs.version }}"
          git push origin HEAD
          git push origin "v${{ steps.bump.outputs.version }}"

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
        env:
          TWINE_NON_INTERACTIVE: true

      - name: Build documentation
        run: mkdocs build --strict

      - name: Deploy documentation
        run: mkdocs gh-deploy --force --remote-branch gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: v${{ steps.bump.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
