name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: version-bump-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump-my-version and jq
        run: |
          pip install bump-my-version==1.2.1
          sudo apt-get update && sudo apt-get install -y jq

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        id: bump
        run: |
          bump-my-version bump patch --allow-dirty
          new_version=$(bump-my-version show current_version --format json | jq -r '.current_version')
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Commit and tag
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Bump version to ${{ steps.bump.outputs.new_version }}"
            git tag "v${{ steps.bump.outputs.new_version }}"
            git push origin HEAD
            git push origin "v${{ steps.bump.outputs.new_version }}"
          else
            echo "No changes to commit"
          fi
